### ISSUE TITLE
clicking icons in left NAV cause blank newtab to open

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#1]
If you click any of the icons in the left nav a blank newtab opens up rather than following the link.

Also should only the text and the icons itself be the active areas or should the whole button box be the active area? If its just the text/icon, should the text/icon color change when its active?

**Comment by funkyeah** [comment]
the click event is only on the a href:

client.coffee (26):     'click a.left-nav': evtNavigate

the icon span is nested under the 'a href'

protobrew.html (139):

``` <nav>

        <ul>

            <li {{#if pageIs "/"}}class="selected"{{/if}}>

                <a class="left-nav" href="/">

                    <span aria-hidden="true" data-icon="&#x68;"></span> Home

                </a>

            </li>

            <li {{#if pageIs "Articles"}}class="selected"{{/if}}>

                <a class="left-nav" href="/Articles">

                    <span aria-hidden="true" data-icon="&#x6e;"></span> Articles

                </a>

            </li>

            <li {{#if pageIs "Brew systems"}}class="selected"{{/if}}>

                <a class="left-nav" href="/Brew systems">

                    <span aria-hidden="true" data-icon="&#xe007;"></span> Brew systems

                </a>

            </li>

        </ul>

    </nav>
```

**Comment by funkyeah** [comment]
changing the css from/to below makes the icons clickable:

```
   #left_nav nav ul li a {

        color: #9a9a9a;

        text-decoration: none;

        transition: color .15s ease-in-out;

        -moz-transition: color .15s ease-in-out;

        -webkit-transition: color .15s ease-in-out;

    }

to

    #left_nav nav ul li a {

        color: #9a9a9a;

        display: block;

        height: 100%;

        width: 100%;

        text-decoration: none;

        transition: color .15s ease-in-out;

        -moz-transition: color .15s ease-in-out;

        -webkit-transition: color .15s ease-in-out;

    }
```

**Comment by funkyeah** [comment]
pushed to repo, up for review - still need to decide if entire button should be clickable or just link and icon (just link and icon are clickable for the moment)

**Comment by sbenhaim** [comment]
The issue is that I was getting evt.target.href, but when clicking on the span containing the icon, the target was the span, rather than the anchor. Here's my fix.

https://github.com/sbenhaim/protobrew/commit/81981137b6ef70327383e3822fb8639d9928767c
