### ISSUE TITLE
blank lines that have headings styles applied to them show up in sidebar

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#10]

**Comment by funkyeah** [comment]
something like this at line 324?

```
    children  =  elem.nextUntil( 'h' + cur, 'h' + next )

    if !(children.text().trim.length)

        children = 0
```

**Comment by funkyeah** [comment]
seems to fix children of h1's but still allows for blank h1's to be rendered due to:

client.coffee(86)  titles = stackTitles( source.find( 'h1' ) )

maybe add a .filter to it with the same jQuery as above?

**Comment by sbenhaim** [comment]
I created a function that filters out headlines that don't contain non-whitespace text.

https://github.com/sbenhaim/protobrew/commit/aecf03cfd1e4391b085349dc82bcf6e4ec27bba7
