### ISSUE TITLE
Setup Company Rackspace Account and point DNS at rackspace

### ISSUE THREAD

**Issue by posborne** [sbenhaim/protobrew#104]
See title.  Hit me up if you have questions.  With the account setup, I can navigate through the rackspace stuff to setup a staging server to start with.  I recommend we setup one staging VM for frequent releases and another production one that actual customers would be served off.

This is a little more expensive.  We can turn off the staging instance some of the time if we don't want to incur the cost.

**Comment by funkyeah** [comment]
think this is more or less done
