### ISSUE TITLE
hitting the edit button cause the window to scroll to the top

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#2]
Reproduce:
1. Partially scroll down an article while logged in.
2. Hit the edit button
3. Observe the window jump back to the top of the article to begin editing

Behavior should be that the scroll position doesn't change and the edits can occur in place

**Comment by funkyeah** [comment]
I have at least one fix that works in chrome:

at client.coffee (123):

if you add:
 viewport_y = window.pageYOffset

before el.redactor(

and 

window.scrollTo(0,viewport_y)

after the redactor call, it seems to work

**Comment by sbenhaim** [comment]
Looks good. Please commit if you haven't yet.

**Comment by funkyeah** [comment]
commited

**Comment by funkyeah** [comment]
does not seem to work after a certain amount down the article

it may be incompatible with the padding bottom fix (e.g. once scrolled into the padding area it does not take that into account when saving the y position)

stepping through debugging show that the browser viewport pops up before the article is rendered

**Comment by funkyeah** [comment]
taken care of in context branch by moving viewport position capture to click event rather than edit render
