### ISSUE TITLE
table of contents autoscroll doesn't work when there is not enough window height

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#3]
known issue:

this one might be a good one for me to look into

**Comment by funkyeah** [comment]
html {padding-bottom: 50%;} ??
would that work as a short term fix?
makes a scroll-bar always appear but that might be better than non-obvious functioning nav for simple short articles (probably the most common at the beginning)

**Comment by sbenhaim** [comment]
The 50% padding solution seems to work. Shall we close this and add an improved version to a list of prospective enhancements?

**Comment by funkyeah** [comment]
added code to automatically add to the window height when clicking something that is too far... resets on navigate
