### ISSUE TITLE
add file upload feature

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#32]
attach files like PDFs etc.

**Comment by sbenhaim** [comment]
Fixed with abe840db19.

**Comment by funkyeah** [comment]
Tried this out and works good but I think it violates user expectations of
file upload. By that I mean I image they would expect the uploaded file to
be attached below (or maybe to the right) of the wiki page, and have
individual delete control, rather than just removal of the link to the
file. Maybe adding the link inline and at the bottom would be acceptable,
but not just inline. Thoughts?
