### ISSUE TITLE
fonts render poorly on default zoom in chrome

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#4]
breaks at 100% and works at 110% on a 1920x1080 desktop monitor and a 1600x900 laptop screen

**Comment by sbenhaim** [comment]
![Screen Shot 2013-03-11 at 3 39 27 PM](https://f.cloud.github.com/assets/6322/245784/d22de3c2-8a8b-11e2-9638-a0acd7bb463f.png)
Rett, are you aware of this? Is this something you want to field?

**Comment by sbenhaim** [comment]
George, is that what you're talking about? Or is there an issue with fonts as well?

**Comment by funkyeah** [comment]
with the change to the new theme this should be fixed
