### ISSUE TITLE
starring a blank page should pop an error message rather than silently fail

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#69]

**Comment by funkyeah** [comment]
fixed in bettinos fork?

https://github.com/abettino/protobrew/commit/8e787b75759b1b9ef2c0155981a074bc09f848c2

8e787b75759b1b9ef2c0155981a074bc09f848c2

**Comment by abettino** [comment]
This should be fixed. Test it out.

**Comment by funkyeah** [comment]
looks good
