### ISSUE TITLE
determine final hosting solution

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#78]

**Comment by funkyeah** [comment]
This one is all you and paul

**Comment by posborne** [comment]
I played around with a few options here, including the PaaS options, but found deploying to my own server to be the easiest and relatively simple to automate.

One thing I think we should definitely considering using for deployment is demeteorizer.  This makes your meteor app look just like a meteor app which removes a bunch of dependencies.  I was able to write a simple deploy script to one of my servers that was relatively straightforward.  It should be wired up to auto-start with something like supervisord or similar for better robustness.

**Comment by funkyeah** [comment]
OK, I did share this with you correct?https://docs.google.com/document/d/1e7P__AtEho4DZJ_NkrXRwngYo5Tn03gEx304q_m_QEA/edit#heading=h.hftv6rj6ant

Two questions
1. I am not too surprised deploying to our own server is the easiest but are we then taking on more responsibility, more difficulty, and/or more effort in the near future to keep availability, redundancy, and scalability? Our most precious resource right now is manpower so optimizing for that and shifting gears once we are profitable I think is the appropriate strategy (even if it costs more).
2. If after considering 1, you determine using our own servers is still the way to go, which one should we go with? 
   I have an account with Linode for the brewery right now but I am happy to use whatever.

**Comment by posborne** [comment]
I haven't given up on the other options.  I had done enough work on dotcloud that I had a pretty nice solution, with the exception that with everything deployed, it didn't work due to the fact that the latest version of node that is supported (at least with the "nodejs" configuration) is 0.8.  Meteor requires something newer.

Heroku looks promising, but I haven't tried it yet.  I agree that there are downsides to hosting it ourselves.  I use rackspace, and I have been relatively happy.

**Comment by funkyeah** [comment]
Yeah check out that  stackoverflow article.  Nodejitsu and modulous.io seem
to be common platforms,  and ec2 and heroku have some sort of deploy
scripts in the wild

**Comment by posborne** [comment]
There are now a couple github threads on this.  While I still feel torn between custom hosting and something like heroku or modulus.io, I feel that hosting on a VPS like rackspace is on the same order of magnitude in terms of complexity and gives us greater control.

The major purported benefits of the other services are ease of use (which I think we can match through automation) and scalability.  The second is a problem I believe we can deal with when we get there.  Rackspace has options for scaling up.  For this app, scaling up big probably means scaling horizontally, which is quite possible given the logical separation between wikis as is the case now and will be the case when multi-tenant as well.
