### ISSUE TITLE
fix comment redactor typeahead and DRY

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#84]
typeahead in comments doesnt work and redactor is initialized twice

**Comment by funkyeah** [comment]
typeahead code catches only redactor in main entry instance
redactor is initialized with code that is largely the same for entries and comments

**Comment by sbenhaim** [comment]
Redactor initialization has been pulled into the _EntryLib class. Typeahead is working for me both in entries and in comments, though I didn't do anything to my knowledge to fix it. It's just supposed to autocomplete for link urls, yes?

c12752eb15e33b50d09d05bf1ebc5e93d4b25812

**Comment by funkyeah** [comment]
yeah, i think the fact that merge the two calls probably fixed the css
selectors the plugin uses
