### ISSUE TITLE
integrate history feature and get basic workable styling done

### ISSUE THREAD

**Issue by funkyeah** [sbenhaim/protobrew#95]

**Comment by posborne** [comment]
There is room for improvement, but I'm willing to call things "good enough" for the next release.

**Comment by funkyeah** [comment]
It doesn't seem to be working for me. I'll test more but here is what I
did...

pulled latest code
meteor reset

re-initialized google login
logged in

modified the homepage and saved 3 times
modified and saved a different pages three times

clicked the history link
history page is blank except for compare selected button

**Comment by posborne** [comment]
I was able to reproduce.  I'll fix.

**Comment by posborne** [comment]
Ok, tis fixed now.

**Comment by funkyeah** [comment]
played with it a bit, looks like a pretty good start to me
